// <auto-generated />
using System;
using App.Modules.Sys.Infrastructure.Domains.Persistence.Relational.EF.DbContexts.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Modules.Sys.Infrastructure.Data.EF.Migrations
{
    [DbContext(typeof(ModuleDbContext))]
    partial class ModuleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Base")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Modules.Sys.Domain.Authorization.SystemPermission", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Key");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_SystemPermissions_Category");

                    b.ToTable("SystemPermissions", "sysmdl");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Authorization.UserSystemPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GrantedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionKey")
                        .HasDatabaseName("IX_UserSystemPermissions_PermissionKey");

                    b.HasIndex("UserId", "PermissionKey")
                        .IsUnique()
                        .HasDatabaseName("IX_UserSystemPermissions_UserId_PermissionKey");

                    b.ToTable("UserSystemPermissions", "sysmdl");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Configuration.SettingValue", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Key")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SerializedTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SerializedTypeValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("WorkspaceId", "UserId", "Key");

                    b.HasIndex("IsLocked")
                        .HasDatabaseName("IX_Settings_IsLocked");

                    b.HasIndex("Key")
                        .HasDatabaseName("IX_Settings_Key");

                    b.HasIndex("WorkspaceId", "Key")
                        .HasDatabaseName("IX_Settings_WorkspaceId_Key");

                    b.ToTable("Settings", "sysmdl");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Identity.IdentityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("IX_IdentityLinks_PersonId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_IdentityLinks_UserId");

                    b.ToTable("IdentityLinks", "sysmdl");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Users_CreatedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.ToTable("Users", "sysmdl");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Identity.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_UserIdentities_Email");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserIdentities_UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserIdentities_Provider_ProviderUserId");

                    b.ToTable("UserIdentities", "sysmdl");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Session.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("TerminatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Sessions_CreatedAt");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Sessions_ExpiresAt");

                    b.HasIndex("SessionToken")
                        .IsUnique()
                        .HasDatabaseName("IX_Sessions_SessionToken");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Sessions_UserId");

                    b.ToTable("Sessions", "sysmdl");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Session.SessionOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("RequestSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("ResponseSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsSuccess")
                        .HasDatabaseName("IX_SessionOperations_IsSuccess");

                    b.HasIndex("OperationType")
                        .HasDatabaseName("IX_SessionOperations_OperationType");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_SessionOperations_SessionId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SessionOperations_Timestamp");

                    b.HasIndex("SessionId", "Timestamp")
                        .HasDatabaseName("IX_SessionOperations_Session_Timestamp");

                    b.ToTable("SessionOperations", "sysmdl");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Workspace.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomCssUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StorageLimitGb")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Free");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Workspaces_IsActive");

                    b.HasIndex("OrganizationName")
                        .HasDatabaseName("IX_Workspaces_OrganizationName");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Workspaces_Slug");

                    b.ToTable("Workspaces", "sysmdl");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System default workspace for initial setup",
                            IsActive = true,
                            MaxUsers = 10,
                            OrganizationName = "Default Organization",
                            PrimaryColor = "#0078D4",
                            Slug = "default",
                            StorageLimitGb = 5,
                            SubscriptionTier = "Free",
                            Title = "Default Workspace",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test workspace for Foo team",
                            IsActive = true,
                            LogoUrl = "https://via.placeholder.com/150/FF6B6B/FFFFFF?text=FOO",
                            MaxUsers = 50,
                            OrganizationName = "Foo Corporation",
                            PrimaryColor = "#FF6B6B",
                            Slug = "foo",
                            StorageLimitGb = 100,
                            SubscriptionTier = "Pro",
                            Title = "Foo Workspace",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomCssUrl = "https://example.com/bar-theme.css",
                            Description = "Test workspace for Bar team",
                            IsActive = true,
                            LogoUrl = "https://via.placeholder.com/150/4ECDC4/FFFFFF?text=BAR",
                            OrganizationName = "Bar Industries",
                            PrimaryColor = "#4ECDC4",
                            Slug = "bar",
                            SubscriptionTier = "Enterprise",
                            Title = "Bar Workspace",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Workspace.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Member");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_WorkspaceMembers_UserId");

                    b.HasIndex("UserId", "IsDefault")
                        .HasDatabaseName("IX_WorkspaceMembers_UserId_IsDefault");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkspaceMembers_WorkspaceId_UserId");

                    b.ToTable("WorkspaceMembers", "sysmdl");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            IsDefault = true,
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Owner",
                            UserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            WorkspaceId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            IsDefault = false,
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin",
                            UserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            WorkspaceId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            IsDefault = false,
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin",
                            UserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            WorkspaceId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            IsDefault = true,
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Member",
                            UserId = new Guid("20000000-0000-0000-0000-000000000002"),
                            WorkspaceId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            IsDefault = false,
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Member",
                            UserId = new Guid("20000000-0000-0000-0000-000000000002"),
                            WorkspaceId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            IsDefault = true,
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Member",
                            UserId = new Guid("20000000-0000-0000-0000-000000000003"),
                            WorkspaceId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            IsDefault = false,
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Guest",
                            UserId = new Guid("20000000-0000-0000-0000-000000000003"),
                            WorkspaceId = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Authorization.UserSystemPermission", b =>
                {
                    b.HasOne("App.Modules.Sys.Domain.Authorization.SystemPermission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Modules.Sys.Domain.Identity.User", "User")
                        .WithMany("SystemPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Identity.IdentityLink", b =>
                {
                    b.HasOne("App.Modules.Sys.Domain.Identity.User", "User")
                        .WithOne("IdentityLink")
                        .HasForeignKey("App.Modules.Sys.Domain.Identity.IdentityLink", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Identity.UserIdentity", b =>
                {
                    b.HasOne("App.Modules.Sys.Domain.Identity.User", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Session.Session", b =>
                {
                    b.HasOne("App.Modules.Sys.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Session.SessionOperation", b =>
                {
                    b.HasOne("App.Modules.Sys.Domain.Session.Session", "Session")
                        .WithMany("Operations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Workspace.WorkspaceMember", b =>
                {
                    b.HasOne("App.Modules.Sys.Domain.Workspace.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Authorization.SystemPermission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Identity.User", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("IdentityLink");

                    b.Navigation("SystemPermissions");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Session.Session", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("App.Modules.Sys.Domain.Workspace.Workspace", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
